---
name: Lint
on:
  push:
jobs:
  build-project:
    name: Lint Project
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Lint Project
        uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          source: '.'
